// 4chan 版块中文名映射；未命中的回退到官方英文 title

export const BOARD_ZH: Record<string, string> = {
  g: '科技',
  a: '动漫',
  c: '萌图',
  w: '动漫壁纸',
  co: '欧美动漫',
  ck: '美食',
  diy: '手工',
  fa: '时尚',
  fit: '健身',
  lit: '文学',
  his: '历史人文',
  int: '国际',
  jp: '二次元综合',
  k: '军武',
  sci: '科学',
  biz: '财经',
  adv: '求助建议',
  an: '动物自然',
  cgl: 'Cosplay',
  cm: '男性向',
  p: '摄影',
  ic: '绘画创作',
  tg: '桌游TCG',
  toy: '玩具',
  trv: '旅行',
  x: '灵异怪谈',
  tv: '影视',
  mu: '音乐',
  v: '游戏',
  vg: '游戏综合',
  vr: '复古游戏',
  vrpg: 'RPG游戏',
  vst: '策略游戏',
  vp: '宝可梦',
  sp: '体育',
  n: '车船',
  o: '汽车',
  '3': '3DCG',
  gd: '平面设计',
  qa: '问答',
  qst: '提问',
  s4s: '趣事',
  pol: '政治',
  news: '新闻',
  wsg: '壁纸综合',
  out: '户外',
  asmr: 'ASMR',
  po: '折纸',
  hr: '高清图',
};

export function boardZh(id: string, fallback: string): string {
  return BOARD_ZH[id] ?? fallback;
}
